language: nix
script: nix-shell .travis/shell.nix --run .travis/test
before_script:
  - nix-shell .travis/shell.nix --run .travis/setup
services:
  - postgresql
environment:
  global:
    - DATABASE_URL=postgres://localhost:5432/conduit
cache:
  directories:
    - $HOME/nix.store
before_install:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
  - mkdir -p $HOME/nix.store
  - nix copy --to file://$HOME/nix.store -f default.nix buildInputs
