name: realworld-conduit
version: 0.1.0.0
synopsis: Exemplary fullstack Medium.com clone powered by Servant and Beam
description: The http://realworld.io specification implemented using Servant for the web application layer and Beam for persistence.
license: BSD3
license-file: LICENSE
author: Brad Parker
maintainer: hi@bradparker.com

ghc-options:
  - -Wall

dependencies:
  - base >=4.10 && <4.12
  - aeson
  - beam-core
  - beam-postgres
  - bytestring
  - containers
  - data-default
  - http-types
  - insert-ordered-containers
  - jose
  - lens
  - monad-control
  - optparse-applicative
  - postgresql-simple
  - resource-pool
  - scrypt
  - servant
  - servant-auth
  - servant-auth-server
  - servant-auth-swagger
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - servant-swagger-ui-core
  - swagger2
  - text
  - time
  - transformers
  - validation
  - wai
  - wai-extra
  - warp

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances

library:
  source-dirs:
    - src
  exposed-modules:
    - RealWorld.Conduit.Attribute
    - RealWorld.Conduit.Database
    - RealWorld.Conduit.Handle
    - RealWorld.Conduit.Options
    - RealWorld.Conduit.Users.Database
    - RealWorld.Conduit.Users.Database.Commands
    - RealWorld.Conduit.Users.Database.Credentials
    - RealWorld.Conduit.Users.Database.Follow
    - RealWorld.Conduit.Users.Database.Queries
    - RealWorld.Conduit.Users.Database.User
    - RealWorld.Conduit.Users.Database.User.Attributes
    - RealWorld.Conduit.Users.Web
    - RealWorld.Conduit.Users.Web.Account
    - RealWorld.Conduit.Users.Web.Claim
    - RealWorld.Conduit.Users.Web.Current
    - RealWorld.Conduit.Users.Web.Current.Update
    - RealWorld.Conduit.Users.Web.Current.View
    - RealWorld.Conduit.Users.Web.Login
    - RealWorld.Conduit.Users.Web.Profile
    - RealWorld.Conduit.Users.Web.Profiles
    - RealWorld.Conduit.Users.Web.Profiles.View
    - RealWorld.Conduit.Users.Web.Profiles.Follow
    - RealWorld.Conduit.Users.Web.Register
    - RealWorld.Conduit.Web
    - RealWorld.Conduit.Web.API
    - RealWorld.Conduit.Web.Auth
    - RealWorld.Conduit.Web.Errors
    - RealWorld.Conduit.Web.Health
    - RealWorld.Conduit.Web.Health.Service
    - RealWorld.Conduit.Web.Namespace
    - RealWorld.Conduit.Web.Swagger

executables:
  realworld-conduit:
    main: Main.hs
    dependencies:
      - realworld-conduit
    source-dirs:
      - app

tests:
  spec:
    main: Spec.hs
    dependencies:
      - hspec
      - hspec-wai
      - hspec-wai-json
      - realworld-conduit
    source-dirs:
      - spec
    other-modules:
      - RealWorld.Conduit.Spec
      - RealWorld.Conduit.Spec.Database
      - RealWorld.Conduit.Spec.Web
      - RealWorld.Conduit.Users.Database.User.AttributesSpec
      - RealWorld.Conduit.Users.DatabaseSpec
      - RealWorld.Conduit.Users.WebSpec
      - Test.Hspec.Wai.Extended
    default-extensions:
      QuasiQuotes
